(define (problem diag-problem)
  (:domain robot-manipulation)
  (:objects step1 step2 - step)
  (:init
    (cube-on-fixture)
    (not (robot-holding))
    (top-face face_f)
    (bottom-face face_b)
    (front-face face_r)
    (back-face face_l)
    (left-face face_d)
    (right-face face_u)
    (current-step step1)
    (next-step step1 step2)
    (step-type-B step1)
  )
  (:goal (and (step-completed step1) (cube-on-fixture) (not (robot-holding))))
)