;;; ============================================================
;;; PROBLEM: rubik-robot-scrambled
;;; ============================================================
(define (problem rubik-robot-scrambled)
  (:domain rubik-robot)
  (:objects
    white yellow red orange blue green - color
    u-ufr u-ufl u-ubr u-ubl d-dfr d-dfl d-dbr d-dbl f-ufr f-ufl f-dfr f-dfl b-ubr b-ubl b-dbr b-dbl l-ufl l-ubl l-dfl l-dbl r-ufr r-ubr r-dfr r-dbr - position
  )
  (:init
    (cube-on-fixture)
    (color-at u-ufr green)
    (color-at u-ufl green)
    (color-at u-ubr white)
    (color-at u-ubl white)
    (color-at d-dfr blue)
    (color-at d-dfl yellow)
    (color-at d-dbr blue)
    (color-at d-dbl yellow)
    (color-at f-ufr red)
    (color-at f-ufl red)
    (color-at f-dfr green)
    (color-at f-dfl yellow)
    (color-at b-ubr orange)
    (color-at b-ubl orange)
    (color-at b-dbr white)
    (color-at b-dbl blue)
    (color-at l-ufl blue)
    (color-at l-ubl white)
    (color-at l-dfl red)
    (color-at l-dbl red)
    (color-at r-ufr yellow)
    (color-at r-ubr green)
    (color-at r-dfr orange)
    (color-at r-dbr orange)
  )
  (:goal (and
    (cube-on-fixture)
    (color-at u-ufr white)
    (color-at u-ufl white)
    (color-at u-ubr white)
    (color-at u-ubl white)
    (color-at d-dfr yellow)
    (color-at d-dfl yellow)
    (color-at d-dbr yellow)
    (color-at d-dbl yellow)
    (color-at f-ufr red)
    (color-at f-ufl red)
    (color-at f-dfr red)
    (color-at f-dfl red)
    (color-at b-ubr orange)
    (color-at b-ubl orange)
    (color-at b-dbr orange)
    (color-at b-dbl orange)
    (color-at l-ufl blue)
    (color-at l-ubl blue)
    (color-at l-dfl blue)
    (color-at l-dbl blue)
    (color-at r-ufr green)
    (color-at r-ubr green)
    (color-at r-dfr green)
    (color-at r-dbr green)
  ))
)